### ISSUE TITLE
Keepalived keeps crashing on Rancher 1.6.2

### ISSUE THREAD

**Issue by FireDrunk** [NeoAssist/docker-keepalived#20]
I've done pretty much everything as documented, and the container seems to start correctly (at start i see the proper config), but the container crashes with the following error(s):
```
10-7-2017 22:05:31Starting Keepalived in the background...
10-7-2017 22:05:31Starting Keepalived v1.2.24 (04/19,2017)
10-7-2017 22:05:31Keepalived[31]: Starting Keepalived v1.2.24 (04/19,2017)
10-7-2017 22:05:31Opening file '/etc/keepalived/keepalived.conf'.
10-7-2017 22:05:31Keepalived[31]: Opening file '/etc/keepalived/keepalived.conf'.
10-7-2017 22:05:31daemon is already running
10-7-2017 22:05:31Keepalived[31]: daemon is already running
10-7-2017 22:05:31/usr/bin/keepalived.sh: line 93: wait: pid 21 is not a child of this shell
10-7-2017 22:05:31pid 33 exited with status 256
10-7-2017 22:05:31Keepalived_vrrp[21]: pid 33 exited with status 256
10-7-2017 22:05:32pid 37 exited with status 256
10-7-2017 22:05:32Keepalived_vrrp[21]: pid 37 exited with status 256
10-7-2017 22:05:32VRRP_Instance(lb-vips) Now in FAULT state
10-7-2017 22:05:32Keepalived_vrrp[21]: VRRP_Instance(lb-vips) Now in FAULT state
10-7-2017 22:05:33pid 41 exited with status 256
10-7-2017 22:05:33Keepalived_vrrp[21]: pid 41 exited with status 256
10-7-2017 22:05:34pid 45 exited with status 256
10-7-2017 22:05:34Keepalived_vrrp[21]: pid 45 exited with status 256
10-7-2017 22:05:35pid 49 exited with status 256
10-7-2017 22:05:35Keepalived_vrrp[21]: pid 49 exited with status 256
10-7-2017 22:05:36pid 53 exited with status 256
10-7-2017 22:05:36Keepalived_vrrp[21]: pid 53 exited with status 256
```

The configuration:
```
version: '2'
services:
  keepalived:
    cap_add:
    - NET_ADMIN
    - NET_BROADCAST
    image: 192.168.1.3:5000/docker-keepalived
    environment:
      CHECK_IP: any
      CHECK_PORT: '80'
      INTERFACE: ens192
      VIRTUAL_IP: 10.0.24.50
      VIRTUAL_MASK: '24'
      VRID: '150'
    stdin_open: true
    network_mode: host
    tty: true
    labels:
      io.rancher.scheduler.global: 'true'
  loadbalancer:
    image: rancher/lb-service-haproxy:v0.7.5
    ports:
    - 0.0.0.0:80:80/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
      io.rancher.scheduler.global: 'true'
```

Any idea?
